### ISSUE TITLE
Не работает с числами

### ISSUE THREAD

**Issue by rptl8sr** [Ilya-goose/Calc_http_go#1]
```
curl --location 'http://localhost:8080/api/v1/calculate' --header 'Content-Type: application/json' --data '{ "expression": "2+21" }'
{"error":"expression is not valid"}
```

**Comment by Ilya-goose** [comment]
Он и не должен работать, калькулятор из прошлого финального задания
обрабатывает только цифры, а числа он не умеет, и нам нигде не говорили
доделывать калькулятор

пн, 23 дек. 2024 г., 23:18 rptl8sr ***@***.***>:

**Comment by rptl8sr** [comment]
а, ну окей тогда, я чёт думал, что он. числами тоже должен
