### ISSUE TITLE
GET-запросы

### ISSUE THREAD

**Issue by MP5s** [Ilya-goose/Calc_http_go#2]
Привет, программа в целом хорошая, прошу лишь только исправить недочет:

> Программа должна принимать только POST-запросы,

У тебя же на самом скриншоте указан GET запрос.
Ниже приложу свой скриншот.
![bugil](https://github.com/user-attachments/assets/26caa193-6d13-400b-bbc8-8da819247844)

>Также порекомендовал бы сделать README-файл более приятным для читателя.
Полезная ссылка: [Форматирование текста](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)

**Comment by Ilya-goose** [comment]
Спасибо за советы
